#############################################################################
# Makefile for building: PFE
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  PFE.pro
# Template: app
# Command: /usr/local/qt5/bin/qmake -o Makefile PFE.pro -spec devices/linux-rasp-pi-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/bin/gcc
CXX           = /usr/bin/g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/qt5/include -I/usr/local/qt5/include/QtCharts -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtSql -I/usr/local/qt5/include/QtCore -I. -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I. -I/usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /usr/local/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PFE1.0.0
DISTDIR = /home/pi/Qt/PFE/.tmp/PFE1.0.0
LINK          = /usr/bin/g++
LFLAGS        = -mfloat-abi=hard -Wl,-O1 -Wl,-rpath,/usr/local/qt5/lib -Wl,-rpath-link,/opt/vc/lib -Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/opt/vc/lib -lwiringPi -L/usr/local/qt5/lib -lQt5Charts -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGLESv2 -lpthread 
AR            = /usr/bin/ar cqs
RANLIB        = 
SED           = sed
STRIP         = /usr/bin/strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_resources.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_resources.o \
		moc_mainwindow.o
DIST          = /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qdevice.pri \
		/usr/local/qt5/mkspecs/features/device_config.prf \
		/usr/local/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/qt5/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/toolchain.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/resources.prf \
		/usr/local/qt5/mkspecs/features/moc.prf \
		/usr/local/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt5/mkspecs/features/uic.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		PFE.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = PFE
DESTDIR       = 
TARGET        = PFE


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PFE.pro /usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qdevice.pri \
		/usr/local/qt5/mkspecs/features/device_config.prf \
		/usr/local/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/qt5/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/toolchain.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/resources.prf \
		/usr/local/qt5/mkspecs/features/moc.prf \
		/usr/local/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt5/mkspecs/features/uic.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		PFE.pro \
		resources.qrc \
		/usr/local/qt5/lib/libQt5Charts.prl \
		/usr/local/qt5/lib/libQt5Widgets.prl \
		/usr/local/qt5/lib/libQt5Gui.prl \
		/usr/local/qt5/lib/libQt5Sql.prl \
		/usr/local/qt5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile PFE.pro -spec devices/linux-rasp-pi-g++
/usr/local/qt5/mkspecs/features/spec_pre.prf:
/usr/local/qt5/mkspecs/common/unix.conf:
/usr/local/qt5/mkspecs/common/linux.conf:
/usr/local/qt5/mkspecs/common/sanitize.conf:
/usr/local/qt5/mkspecs/common/gcc-base.conf:
/usr/local/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt5/mkspecs/common/g++-base.conf:
/usr/local/qt5/mkspecs/common/g++-unix.conf:
/usr/local/qt5/mkspecs/qdevice.pri:
/usr/local/qt5/mkspecs/features/device_config.prf:
/usr/local/qt5/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/qt5/mkspecs/devices/common/linux_device_post.conf:
/usr/local/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/qt5/mkspecs/qconfig.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/local/qt5/mkspecs/features/qt_functions.prf:
/usr/local/qt5/mkspecs/features/qt_config.prf:
/usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/usr/local/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/qt5/mkspecs/features/toolchain.prf:
/usr/local/qt5/mkspecs/features/default_pre.prf:
/usr/local/qt5/mkspecs/features/resolve_config.prf:
/usr/local/qt5/mkspecs/features/default_post.prf:
/usr/local/qt5/mkspecs/features/warn_on.prf:
/usr/local/qt5/mkspecs/features/qt.prf:
/usr/local/qt5/mkspecs/features/resources.prf:
/usr/local/qt5/mkspecs/features/moc.prf:
/usr/local/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/qt5/mkspecs/features/uic.prf:
/usr/local/qt5/mkspecs/features/unix/thread.prf:
/usr/local/qt5/mkspecs/features/qmake_use.prf:
/usr/local/qt5/mkspecs/features/file_copies.prf:
/usr/local/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/qt5/mkspecs/features/exceptions.prf:
/usr/local/qt5/mkspecs/features/yacc.prf:
/usr/local/qt5/mkspecs/features/lex.prf:
PFE.pro:
resources.qrc:
/usr/local/qt5/lib/libQt5Charts.prl:
/usr/local/qt5/lib/libQt5Widgets.prl:
/usr/local/qt5/lib/libQt5Gui.prl:
/usr/local/qt5/lib/libQt5Sql.prl:
/usr/local/qt5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PFE.pro -spec devices/linux-rasp-pi-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/local/qt5/bin/rcc \
		down_arrow.png \
		handle.png \
		checkbox.png \
		dark.qss
	/usr/local/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/qt5/mkspecs/features/data/dummy.cpp
	/usr/bin/g++ -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -Wall -W -dM -E -o moc_predefs.h /usr/local/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/qt5/include/QtWidgets/QMainWindow \
		/usr/local/qt5/include/QtWidgets/qmainwindow.h \
		/usr/local/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt5/include/QtGui/qtguiglobal.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qtcore-config.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtGui/qtgui-config.h \
		/usr/local/qt5/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringliteral.h \
		/usr/local/qt5/include/QtCore/qstringalgorithms.h \
		/usr/local/qt5/include/QtCore/qstringview.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtSql/QSqlDatabase \
		/usr/local/qt5/include/QtSql/qsqldatabase.h \
		/usr/local/qt5/include/QtSql/qtsqlglobal.h \
		/usr/local/qt5/include/QtCore/QElapsedTimer \
		/usr/local/qt5/include/QtCore/qelapsedtimer.h \
		/usr/local/qt5/include/QtCore/QThread \
		/usr/local/qt5/include/QtCore/qthread.h \
		/usr/local/qt5/include/QtCore/QDate \
		/usr/local/qt5/include/QtCore/qdatetime.h \
		/usr/local/qt5/include/QtSql/QSqlTableModel \
		/usr/local/qt5/include/QtSql/qsqltablemodel.h \
		/usr/local/qt5/include/QtSql/qsqlquerymodel.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/QFile \
		/usr/local/qt5/include/QtCore/QTimer \
		/usr/local/qt5/include/QtCore/qtimer.h \
		/usr/local/qt5/include/QtCore/qbasictimer.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/local/qt5/bin/moc
	/usr/local/qt5/bin/moc $(DEFINES) --include /home/pi/Qt/PFE/moc_predefs.h -I/usr/local/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/home/pi/Qt/PFE -I/usr/local/qt5/include -I/usr/local/qt5/include/QtCharts -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtSql -I/usr/local/qt5/include/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/qt5/bin/uic
	/usr/local/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/qt5/include/QtWidgets/QMainWindow \
		/usr/local/qt5/include/QtWidgets/qmainwindow.h \
		/usr/local/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt5/include/QtGui/qtguiglobal.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qtcore-config.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtGui/qtgui-config.h \
		/usr/local/qt5/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringliteral.h \
		/usr/local/qt5/include/QtCore/qstringalgorithms.h \
		/usr/local/qt5/include/QtCore/qstringview.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtSql/QSqlDatabase \
		/usr/local/qt5/include/QtSql/qsqldatabase.h \
		/usr/local/qt5/include/QtSql/qtsqlglobal.h \
		/usr/local/qt5/include/QtCore/QElapsedTimer \
		/usr/local/qt5/include/QtCore/qelapsedtimer.h \
		/usr/local/qt5/include/QtCore/QThread \
		/usr/local/qt5/include/QtCore/qthread.h \
		/usr/local/qt5/include/QtCore/QDate \
		/usr/local/qt5/include/QtCore/qdatetime.h \
		/usr/local/qt5/include/QtSql/QSqlTableModel \
		/usr/local/qt5/include/QtSql/qsqltablemodel.h \
		/usr/local/qt5/include/QtSql/qsqlquerymodel.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/QFile \
		/usr/local/qt5/include/QtCore/QTimer \
		/usr/local/qt5/include/QtCore/qtimer.h \
		/usr/local/qt5/include/QtCore/qbasictimer.h \
		/usr/local/qt5/include/QtWidgets/QApplication \
		/usr/local/qt5/include/QtWidgets/qapplication.h \
		/usr/local/qt5/include/QtCore/qcoreapplication.h \
		/usr/local/qt5/include/QtCore/qeventloop.h \
		/usr/local/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt5/include/QtGui/qguiapplication.h \
		/usr/local/qt5/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/qt5/include/QtWidgets/QMainWindow \
		/usr/local/qt5/include/QtWidgets/qmainwindow.h \
		/usr/local/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt5/include/QtGui/qtguiglobal.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qtcore-config.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtGui/qtgui-config.h \
		/usr/local/qt5/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringliteral.h \
		/usr/local/qt5/include/QtCore/qstringalgorithms.h \
		/usr/local/qt5/include/QtCore/qstringview.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtSql/QSqlDatabase \
		/usr/local/qt5/include/QtSql/qsqldatabase.h \
		/usr/local/qt5/include/QtSql/qtsqlglobal.h \
		/usr/local/qt5/include/QtCore/QElapsedTimer \
		/usr/local/qt5/include/QtCore/qelapsedtimer.h \
		/usr/local/qt5/include/QtCore/QThread \
		/usr/local/qt5/include/QtCore/qthread.h \
		/usr/local/qt5/include/QtCore/QDate \
		/usr/local/qt5/include/QtCore/qdatetime.h \
		/usr/local/qt5/include/QtSql/QSqlTableModel \
		/usr/local/qt5/include/QtSql/qsqltablemodel.h \
		/usr/local/qt5/include/QtSql/qsqlquerymodel.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/QFile \
		/usr/local/qt5/include/QtCore/QTimer \
		/usr/local/qt5/include/QtCore/qtimer.h \
		/usr/local/qt5/include/QtCore/qbasictimer.h \
		ui_mainwindow.h \
		/usr/local/qt5/include/QtCore/QVariant \
		/usr/local/qt5/include/QtWidgets/QApplication \
		/usr/local/qt5/include/QtWidgets/qapplication.h \
		/usr/local/qt5/include/QtCore/qcoreapplication.h \
		/usr/local/qt5/include/QtCore/qeventloop.h \
		/usr/local/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt5/include/QtGui/qguiapplication.h \
		/usr/local/qt5/include/QtGui/qinputmethod.h \
		/usr/local/qt5/include/QtWidgets/QCheckBox \
		/usr/local/qt5/include/QtWidgets/qcheckbox.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtWidgets/QComboBox \
		/usr/local/qt5/include/QtWidgets/qcombobox.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtWidgets/QGridLayout \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtWidgets/QGroupBox \
		/usr/local/qt5/include/QtWidgets/qgroupbox.h \
		/usr/local/qt5/include/QtWidgets/QHBoxLayout \
		/usr/local/qt5/include/QtWidgets/QHeaderView \
		/usr/local/qt5/include/QtWidgets/qheaderview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/QLabel \
		/usr/local/qt5/include/QtWidgets/qlabel.h \
		/usr/local/qt5/include/QtWidgets/QLineEdit \
		/usr/local/qt5/include/QtWidgets/qlineedit.h \
		/usr/local/qt5/include/QtGui/qtextcursor.h \
		/usr/local/qt5/include/QtGui/qtextformat.h \
		/usr/local/qt5/include/QtGui/qpen.h \
		/usr/local/qt5/include/QtGui/qtextoption.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/QSpacerItem \
		/usr/local/qt5/include/QtWidgets/QSplitter \
		/usr/local/qt5/include/QtWidgets/qsplitter.h \
		/usr/local/qt5/include/QtWidgets/QTabWidget \
		/usr/local/qt5/include/QtWidgets/QTableView \
		/usr/local/qt5/include/QtWidgets/qtableview.h \
		/usr/local/qt5/include/QtWidgets/QVBoxLayout \
		/usr/local/qt5/include/QtWidgets/QWidget \
		/usr/local/qt5/include/QtSql/QSqlError \
		/usr/local/qt5/include/QtSql/qsqlerror.h \
		/usr/local/qt5/include/QtSql/QSqlQuery \
		/usr/local/qt5/include/QtSql/qsqlquery.h \
		/usr/local/qt5/include/QtWidgets/QMessageBox \
		/usr/local/qt5/include/QtWidgets/qmessagebox.h \
		/usr/local/qt5/include/QtWidgets/qdialog.h \
		/usr/local/qt5/include/QtCore/QDebug \
		/usr/local/qt5/include/QtCharts/QSplineSeries \
		/usr/local/qt5/include/QtCharts/qsplineseries.h \
		/usr/local/qt5/include/QtCharts/QChartGlobal \
		/usr/local/qt5/include/QtCharts/qchartglobal.h \
		/usr/local/qt5/include/QtCore/QtGlobal \
		/usr/local/qt5/include/QtCharts/qlineseries.h \
		/usr/local/qt5/include/QtCharts/QXYSeries \
		/usr/local/qt5/include/QtCharts/qxyseries.h \
		/usr/local/qt5/include/QtCharts/QAbstractSeries \
		/usr/local/qt5/include/QtCharts/qabstractseries.h \
		/usr/local/qt5/include/QtCharts/QAbstractAxis \
		/usr/local/qt5/include/QtCharts/qabstractaxis.h \
		/usr/local/qt5/include/QtGui/QPen \
		/usr/local/qt5/include/QtGui/QFont \
		/usr/local/qt5/include/QtCore/QObject \
		/usr/local/qt5/include/QtGui/QBrush \
		/usr/local/qt5/include/QtCore/QList \
		/usr/local/qt5/include/QtCore/QPointF \
		/usr/local/qt5/include/QtCharts/QChart \
		/usr/local/qt5/include/QtCharts/qchart.h \
		/usr/local/qt5/include/QtCharts/QLegend \
		/usr/local/qt5/include/QtCharts/qlegend.h \
		/usr/local/qt5/include/QtWidgets/QGraphicsWidget \
		/usr/local/qt5/include/QtWidgets/qgraphicswidget.h \
		/usr/local/qt5/include/QtWidgets/qgraphicslayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qgraphicsitem.h \
		/usr/local/qt5/include/QtCore/QMargins \
		/usr/local/qt5/include/QtCharts/QChartView \
		/usr/local/qt5/include/QtCharts/qchartview.h \
		/usr/local/qt5/include/QtWidgets/QGraphicsView \
		/usr/local/qt5/include/QtWidgets/qgraphicsview.h \
		/usr/local/qt5/include/QtGui/qpainter.h \
		/usr/local/qt5/include/QtWidgets/qscrollarea.h \
		/usr/local/qt5/include/QtWidgets/qgraphicsscene.h \
		/usr/local/qt5/include/QtWidgets/QLayout \
		/usr/local/qt5/include/QtCharts/QDateTimeAxis \
		/usr/local/qt5/include/QtCharts/qdatetimeaxis.h \
		/usr/local/qt5/include/QtCharts/QValueAxis \
		/usr/local/qt5/include/QtCharts/qvalueaxis.h \
		/usr/local/qt5/include/QtWidgets/QInputDialog \
		/usr/local/qt5/include/QtWidgets/qinputdialog.h \
		/usr/local/qt5/include/QtCore/QDir \
		/usr/local/qt5/include/QtCore/qdir.h \
		/usr/local/qt5/include/QtCore/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

